name: Assign Pull Request Creator

on:
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - 'main'
      - 'stable'
      - 'release/v*'

jobs:
  assign-assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Assign PR creator
        uses: dafneb/.github/.github/workflows/pull-request-assignee.yml@main
        with:
          assignees: ${{ github.actor }}
        secrets: inherit
